### ISSUE TITLE
Server Banners not appearing

### ISSUE THREAD

**Issue by TheCosmicNebula** [DevEvil99/DarkPlus-Defualt-Memberlist#1]
I am using the Dark+ Theme with the default memberlist and server banners are not being shown.
![image](https://user-images.githubusercontent.com/33880828/224115959-0ca7b332-27ae-4964-8d0d-677393c52dd4.png)

![image](https://user-images.githubusercontent.com/33880828/224115897-879c9cc2-6f0e-4936-a091-acbdbcbdf777.png)

**Comment by DevEvil99** [comment]
its fixed, next time report on discord server or the official version of the theme, I don't see these reports
